# https://travis-ci.org/luchko/latticegraph_designer

language: python
#sudo: false

env:
  global:
    - MINICONDA_VERSION="latest"
    - MINICONDA_LINUX="Linux-x86_64"
    - MINICONDA_OSX="MacOSX-x86_64"

matrix:
  include:
    # Linux using pip packages
    - python: "3.5"
      env: USE_QT_API=PyQt5 USE_CONDA=false
      os: linux
    # Linux using conda packages
    - python: "2.7"
      env: USE_QT_API=PyQt4 USE_CONDA=true
      os: linux
    - python: "2.7"
      env: USE_QT_API=PyQt5 USE_CONDA=true
      os: linux
    - python: "3.6"
      env: USE_QT_API=PyQt4 USE_CONDA=true
      os: linux
    - python: "3.6"
      env: USE_QT_API=PyQt5 USE_CONDA=true
      os: linux
  
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
install:
  - ./continuous_integration/install.sh;

script:
  - python -m unittest discover
#  - python setup.py test
  
